language: python

python:
 - "3.5"

install:
 - pip install --upgrade pip
 - pip install django
 - pip install -U pytest
 - pip install pytest-cov
 - pip install factory_boy
 - echo $PYTHONPATH

script: PYTHONPATH=. pytest